### PR TITLE
Add images from the Rider-Smith-Waite deck.

### PR DESCRIPTION
**Pull request by linkel**
Hi Ekelen! 

I know this is a pretty old repo, but I think it's cool that it's the first result for tarot API when searching on Github. I found a site that had clearly-scanned images of the Rider Smith Waite deck pictures and had compiled them into a folder previously. 

Figured it wouldn't be too difficult to align them with your key naming and throw them in a folder in case it'd be interesting. It's not hooked up, alas, and I haven't thought much about how you'd host the images, but here you go. 

-linkel

### CODE REVIEW

**Comment by caleb-cox** [comment]
Hey, just wanted to put this out there, since it _might_ be helpful to you. I just stumbled upon this API, and I'm really glad I did! I'm using it for a Discord bot, and I wanted to include images as well.

Since this API is using data from https://www.sacred-texts.com/tarot/pkt/index.htm, I went poking around in there and found you can actually really easily get images using data from this API as-is. They're not _quite_ as good as the high-res scans you includes (I have the same images saved on my desktop lol), but it's pretty serviceable for my purposes and may be for yours as well.

You just have to interpolate the response card's `name_short` into a URL like so (I'm using JavaScript...):
```javascript
`https://www.sacred-texts.com/tarot/pkt/img/${card.name_short}.jpg`
```

The naming convention matches up, which is really neat. Hope this is useful to you!

**Comment by linkel** [comment]
@caleb-cox That's awesome! Ha, maybe we can make a PR to add that to the README file. Out of curiosity (if you're willing to share) what community is the Discord bot for?

**Comment by caleb-cox** [comment]
@linkel It's not even for a proper community. Just some experiments in game design for myself and a few friends!

**Comment by msbeethoven** [comment]
@caleb-cox  thanks for pointing this out! As someone else who was curious about creating a pr for images, did you find that you ended up just using the sacred-texts api instead since it has the images? There isn't a way to have the images show up, even with the `name_short` attribute in this tarot-api, right?

**Comment by ekelen** [comment]
Sorry for the superduper late followup @linkel + @caleb-cox ! I meant to add images one way or another at some point and these are dope. I'd be hesitant to add the media to the repo as it would make it considerably larger, but it's pretty darn cool to have them. Thanks for the thoughtful discussion & contribution. 

I'll keep this open for now; anyone stumbling upon this who wants images should merge this locally in the likely overlong interim.

**Comment by ekelen** [comment]
Closing but not forgotten. This is a cool idea, but would increase the size of the repo too much.

**Pull request closed without merging**
